### ISSUE TITLE
One content creator to the next

### ISSUE THREAD

**Issue by DarcyManoel** [ItsNickBarry/endless-sky-flamethrower-turret#2]
@ItsNickBarry Could I have your permission to include the Flamethrower Turret in my plugin (with credits to you of course)? Also if it's not to much of an ask is there somewhere I could find the blend of it?

**Comment by ItsNickBarry** [comment]
The images and code are released under an open source license, which can be found in the `copyright` file.  You're free to do just about anything you want.

Attached are the `.blend` and `.xcf` (GIMP) files.  The latter contains a rendering of the model as well as the texture layers.

[flamethrower.zip](https://github.com/ItsNickBarry/endless-sky-flamethrower-turret/files/2216863/flamethrower.zip)
