### ISSUE TITLE
Feature Request: Adding a ramscoop to increase combat duration

### ISSUE THREAD

**Issue by ApolloX939** [ItsNickBarry/endless-sky-flamethrower-turret#6]
Currently the ship will eventually run out of fuel... and thus need to land at a inhabited planet to refuel.

This request will provide a ramscoop to the turret... which means the turret will essentially replenish fuel while the ship is in flight. (Regardless of if the turret is firing or not, it just needs to be installed)

The attached is the new data/weapons.txt file with the purposed change.

[weapons.txt](https://github.com/ItsNickBarry/endless-sky-flamethrower-turret/files/5874852/weapons.txt)

**Comment by ItsNickBarry** [comment]
I am inclined to think that it's the captain's responsibility to ensure that the ship does not run out of fuel.  This plugin was considered too overpowered to be included in the base game, and adding a built-in ramscoop only makes it more so.

**Comment by ItsNickBarry** [comment]
I added some text to the weapon description suggesting that the turret be used with a separate ramscoop.

**Comment by ApolloX939** [comment]
Now that I have personally used this mod I agree with not having a builtin ramscoop. (If the cap didn't think of one then they are going to learn)
